SELECT USER
FROM DUAL;


-- 회원
-- MEMBER

SELECT * 
FROM MEMBER;

DELETE
FROM MEMBER;

INSERT INTO MEMBER(MEM_ID, MEM_NAME, MEM_ID_ID, MEM_PW, MEM_TEL, MEM_SSN1, MEM_SSN2, MEM_NICKNAME, MEM_ZIPCODE, MEM_ADDR
, MEM_ADDR_DETAIL, MEM_LATITUDE, MEM_LONGTITUDE, MEM_IMG, TMP_MEMBER_ID)
VALUES(SEQ_MEMBER.NEXTVAL, '홍길동', 'kiwifirst', 'JAVA002$', '01011111111', '221231','1111111', '키위첫번째', 67890, 
'서울시 마포구 111-11 길', '101호', '37.556556', '126.919550'
, 'C://~~', 100);

INSERT INTO MEMBER(MEM_ID, MEM_NAME, MEM_ID_ID, MEM_PW, MEM_TEL, MEM_SSN1, MEM_SSN2, MEM_NICKNAME, MEM_ZIPCODE, MEM_ADDR
, MEM_ADDR_DETAIL, MEM_LATITUDE, MEM_LONGTITUDE, MEM_IMG, TMP_MEMBER_ID)
VALUES(SEQ_MEMBER.NEXTVAL, '아이유', 'kiwisecond', 'kiwi222', '0102222222', '121231','22222221', '키위첫번째', 12345, 
'서울시 마포구 222-22 길', '102호', '37.555505', '126.921454'
, 'C://~~', 101);

COMMIT;

ROLLBACK;
DROP SEQUENCE SEQ_MEMBER;

CREATE SEQUENCE SEQ_MEMBER
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;



DESC PET_SHARE;

SELECT *
FROM PET_SHARE;



-- 임의 회원 코드 발급
-- TMP_MEM
CREATE SEQUENCE SEQ_TMP_MEM
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;


DROP SEQUENCE SEQ_TMP_MEM;

SELECT *
FROM TMP_MEM;


DELETE
FROM TMP_MEM;


DESC TMP_MEM;

INSERT INTO TMP_MEM(T_MEM_ID, T_MEM_DATE, T_MEM_ALA_DATE)
VALUES (SEQ_TMP_MEM.NEXTVAL, DEFAULT, NULL);
INSERT INTO TMP_MEM(T_MEM_ID, T_MEM_DATE, T_MEM_ALA_DATE)
VALUES (SEQ_TMP_MEM.NEXTVAL, DEFAULT, NULL);



-- 쪽지
-- NOTE

SELECT *
FROM NOTE;

DELETE
FROM NOTE;

DESC NOTE;

CREATE SEQUENCE SEQ_NOTE
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;


-- 기존의 컬럼에 Default값 설정하기
ALTER TABLE NOTE MODIFY N_READ_DATE DEFAULT NULL;
ALTER TABLE NOTE MODIFY N_SEND_DEL_DATE DEFAULT NULL;
ALTER TABLE NOTE MODIFY N_READ_DEL_DATE DEFAULT NULL;


INSERT INTO NOTE(N_ID, N_CONTENT, N_SEND_DATE, N_READ_DATE, N_SEND_DEL_DATE, N_READ_DEL_DATE, N_SEND_MEM_ID, N_READ_MEM_ID)
VALUES (SEQ_NOTE.NEXTVAL, '새해 복 많이 받으세욥', SYSDATE, NULL, NULL, NULL, 102, 103);
INSERT INTO NOTE(N_ID, N_CONTENT, N_SEND_DATE, N_READ_DATE, N_SEND_DEL_DATE, N_READ_DEL_DATE, N_SEND_MEM_ID, N_READ_MEM_ID)
VALUES (SEQ_NOTE.NEXTVAL, '아이유가 홍길동에게', SYSDATE, NULL, NULL, NULL, 103, 102);

COMMIT;


-- 신고처리
-- REP_PROCESS

SELECT *
FROM REP_PROCESS;

DELETE
FROM REP_PROCESS;

DESC REP_PROCESS;


INSERT INTO REP_PROCESS(R_PRO_ID, R_PRO_TYPE)
VALUES(1, '무효');
INSERT INTO REP_PROCESS(R_PRO_ID, R_PRO_TYPE)
VALUES(2, '경고');

COMMIT;

-- 쪽지 신고
-- NOTE_REPORT

SELECT *
FROM NOTE_REPORT;

DESC NOTE_REPORT;

DROP SEQUENCE SEQ_NOTE_REPORT;

CREATE SEQUENCE SEQ_NOTE_REPORT
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;

INSERT INTO NOTE_REPORT(N_REP_ID, N_REP_TITLE, N_REP_CONTENT, N_REP_DATE, N_REP_PRO_DATE, N_REP_PRO_ADM_ID, N_ID, R_PRO_ID)
VALUES (SEQ_NOTE_REPORT.NEXTVAL, '신고합니다!', '쪽지 내용보고 처리좀 해주세요', SYSDATE, NULL, NULL, 101, NULL);


-- 기존의 컬럼에 Default값 설정하기
--는 안함

COMMIT;

INSERT INTO NOTE_REPORT(N_REP_ID, N_REP_TITLE, N_REP_CONTENT, N_REP_DATE, N_REP_PRO_DATE, N_REP_PRO_ADM_ID, N_ID, R_PRO_ID)
VALUES (SEQ_NOTE_REPORT.NEXTVAL, ?, ?, SYSDATE, NULL, NULL, 101, NULL);

SELECT *
FROM TMP_MEM;


-- 문의하기
-- QUESTION

SELECT *
FROM QUESTION;

DELETE
FROM QUESTION;

DESC QUESTION;

DROP SEQUENCE SEQ_QUESTION;

CREATE SEQUENCE SEQ_QUESTION
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;

INSERT INTO QUESTION(Q_ID, Q_SUBJECT, Q_CONTENT, Q_DATE, Q_PWD, T_MEM_ID)
VALUES (SEQ_QUESTION.NEXTVAL, '서비스중에 궁금한게있어요', '제가 서비스를 신청했는데 궁금한게 생겼습니다 그리고 이러이러한 서비스도 가능한지 궁금합니다.'
, SYSDATE, '1234', 'UV8YF0IN08');
INSERT INTO QUESTION(Q_ID, Q_SUBJECT, Q_CONTENT, Q_DATE, Q_PWD, T_MEM_ID)
VALUES (SEQ_QUESTION.NEXTVAL, '서비스가격이 내년엔 오르나요?', ' - 긴급서비스_방문- 쪽지, 쪽지신고 - 문의하기,답변하기.기능이 다양해서 만족하고있습니다. 내년엔 오르나요?'
, SYSDATE, '1111', 'UV8YF0IN08');

COMMIT;


INSERT INTO QUESTION(Q_ID, Q_SUBJECT, Q_CONTENT, Q_DATE, Q_PWD, T_MEM_ID)
VALUES (SEQ_QUESTION.NEXTVAL, ?, ?, SYSDATE, ?, ?);
INSERT INTO QUESTION(Q_ID, Q_SUBJECT, Q_CONTENT, Q_DATE, Q_PWD, T_MEM_ID)
VALUES (SEQ_QUESTION.NEXTVAL, ?, ?, SYSDATE, ?, ?);

-- 답변하기
-- ANSWER

SELECT *
FROM ANSWER;


DELETE
FROM ANSWER;

DESC ANSWER;

DROP SEQUENCE SEQ_ANSWER;

CREATE SEQUENCE SEQ_ANSWER
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;

INSERT INTO ANSWER(A_ID, A_CONTENT, A_DATE, A_ADM_ID, Q_ID)
VALUES (SEQ_ANSWER.NEXTVAL, '서비스 이용감사드립니다. 문의해주신 서비스는 이러이렇게 신청하시면 됩니다.', SYSDATE, 'kiwi',102);
INSERT INTO ANSWER(A_ID, A_CONTENT, A_DATE, A_ADM_ID, Q_ID)
VALUES (SEQ_ANSWER.NEXTVAL, '서비스 이용감사드립니다. 문의해주신 가격은 2023년 까지는 변동예정이 없습니다.', SYSDATE, 'kiwi',103);

COMMIT;

INSERT INTO ANSWER(A_ID, A_CONTENT, A_DATE, A_ADM_ID, Q_ID)
VALUES (SEQ_ANSWER.NEXTVAL, ?, SYSDATE, ?, ?);
INSERT INTO ANSWER(A_ID, A_CONTENT, A_DATE, A_ADM_ID, Q_ID)
VALUES (SEQ_ANSWER.NEXTVAL, ?, SYSDATE, ?, ?);



-- 긴급 서비스요청 _방문
-- U_V

SELECT *
FROM U_V;

DELETE
FROM U_V;

DROP SEQUENCE SEQ_U_V;

CREATE SEQUENCE SEQ_U_V
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;

SELECT *
FROM PAY;


INSERT INTO U_V(U_V_ID, U_V_CLI_ZIPCODE, U_V_CLI_ADDR, U_V_CLI_ADDR_DETAIL, U_V_LATITUDE, U_V_LONGITUDE, U_V_START_DATE, U_V_END_DATE, U_V_REQ_DATE
, U_V_REQ_TERM, U_V_REQ_TITLE, C_TYPE_ID, P_ID)
VALUES (SEQ_U_V.NEXTVAL, '67890', '서울시 마포구 111-11 길', '101호', '37.556556', '126.919550', TO_DATE('2023-01-18 00:12:00', 'YYYY-MM-DD HH24:MI:SS')
, TO_DATE('2023-01-19 00:12:00', 'YYYY-MM-DD HH24:MI:SS'), SYSDATE, '저희 아이 잘 봐주실 분 구합니다 자세한건 쪽지로 해요'
, '새해복 많이 받으세요', 1, 100);
INSERT INTO U_V(U_V_ID, U_V_CLI_ZIPCODE, U_V_CLI_ADDR, U_V_CLI_ADDR_DETAIL, U_V_LATITUDE, U_V_LONGITUDE, U_V_START_DATE, U_V_END_DATE, U_V_REQ_DATE
, U_V_REQ_TERM, U_V_REQ_TITLE, C_TYPE_ID, P_ID)
VALUES (SEQ_U_V.NEXTVAL, '12345', '서울시 마포구 222-22 길', '102호', '37.556550', '126.919545', TO_DATE('2023-01-19 00:12:00', 'YYYY-MM-DD HH24:MI:SS')
, TO_DATE('2023-01-20 00:19:00', 'YYYY-MM-DD HH24:MI:SS'), SYSDATE, '서비스를 처음이용하는데 믿고 맡깁니다.'
, '이틀간 가족처럼 봐주실분!!', 2, 100);


SELECT *
FROM CARE_TYPE;

COMMIT;

INSERT INTO U_V(U_V_ID, U_V_CLI_ZIPCODE, U_V_CLI_ADDR, U_V_CLI_ADDR_DETAIL, U_V_LATITUDE, U_V_LONGITUDE, U_V_START_DATE, U_V_END_DATE, U_V_REQ_DATE
, U_V_REQ_TERM, U_V_REQ_TITLE, C_TYPE_ID, P_ID)
VALUES (SEQ_U_V.NEXTVAL, ?, ?, ?, ?, ?, ?, ?, SYSDATE, ?, ?, ?, ?);


-- 긴급 서비스_방문 지원
-- U_V_APPLY

SELECT *
FROM U_V_APPLY;


DESC U_V_APPLY;

DROP SEQUENCE SEQ_U_V_APPLY;

CREATE SEQUENCE SEQ_U_V_APPLY
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;

INSERT INTO U_V_APPLY(U_V_APP_ID, U_V_APP_DATE, U_V_ID, S_ALL_ID)
VALUES (SEQ_U_V_APPLY.NEXTVAL, SYSDATE, 100, 100);
INSERT INTO U_V_APPLY(U_V_APP_ID, U_V_APP_DATE, U_V_ID, S_ALL_ID)
VALUES (SEQ_U_V_APPLY.NEXTVAL, SYSDATE, U_V_ID,101);

COMMIT;


INSERT INTO U_V_APPLY(U_V_APP_ID, U_V_APP_DATE, U_V_ID, S_ALL_ID)
VALUES (SEQ_U_V_APPLY.NEXTVAL, SYSDATE, ?, ?);


SELECT *
FROM S_ALLOW;

-- 긴급서비스_ 방문 확정
-- U_V_CONFIRM


SELECT *
FROM U_V_CONFIRM;

DESC U_V_CONFIRM;

DROP SEQUENCE SEQ_U_V_CONFIRM;

CREATE SEQUENCE SEQ_U_V_CONFIRM
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;


INSERT INTO U_V_CONFIRM(U_V_CON_ID, U_V_REV_TITLE, U_V_REV_CONTENT, U_V_REV_DATE, U_V_REV_IMG1, U_V_REV_IMG2, U_V_REV_IMG3
, U_V_CON_DATE, STAR_RAT_ID, U_V_RES_ID, CT_ID)
VALUES (SEQ_U_V_CONFIRM.NEXTVAL, NULL, NULL, NULL, NULL, NULL, NULL, SYSDATE, NULL, U_V_RES_ID, 1);
INSERT INTO U_V_CONFIRM(U_V_CON_ID, U_V_REV_TITLE, U_V_REV_CONTENT, U_V_REV_DATE, U_V_REV_IMG1, U_V_REV_IMG2, U_V_REV_IMG3
, U_V_CON_DATE, STAR_RAT_ID, U_V_RES_ID, CT_ID)
VALUES (SEQ_U_V_CONFIRM.NEXTVAL, '참 마음에드네요', '키위라는 서비스 SNS를 통해 알게되었습니다.'
, U_V_CON_DATE, NULL, NULL, NULL, SYSDATE, 5, U_V_RES_ID, 2);
INSERT INTO U_V_CONFIRM(U_V_CON_ID, U_V_REV_TITLE, U_V_REV_CONTENT, U_V_REV_DATE, U_V_REV_IMG1, U_V_REV_IMG2, U_V_REV_IMG3
, U_V_CON_DATE, STAR_RAT_ID, U_V_RES_ID, CT_ID)
VALUES (SEQ_U_V_CONFIRM.NEXTVAL, NULL, NULL, NULL, NULL, NULL, NULL, SYSDATE, NULL, 100, 3);


COMMIT;

INSERT INTO U_V_CONFIRM(U_V_CON_ID, U_V_REV_TITLE, U_V_REV_CONTENT, U_V_REV_DATE, U_V_REV_IMG1, U_V_REV_IMG2, U_V_REV_IMG3
, U_V_CON_DATE, STAR_RAT_ID, U_V_RES_ID, CT_ID)
VALUES (SEQ_U_V_CONFIRM.NEXTVAL, NULL, NULL, NULL, NULL, NULL, NULL, SYSDATE, NULL, ?, ?);

SELECT *
FROM STAR_RATE;

SELECT *
FROM CON_TYPE;



-- 긴급서비스_방문 예약완료
-- U_V_RESERV


SELECT *
FROM U_V_RESERV;

DESC U_V_RESERV;

DROP SEQUENCE SEQ_U_V_RESERV;

CREATE SEQUENCE SEQ_U_V_RESERV
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;



INSERT INTO U_V_RESERV(U_V_RES_ID, U_V_RES_DATE, U_V_APP_ID)
VALUES (SEQ_U_V_RESERV.NEXTVAL, SYSDATE, 102);
INSERT INTO U_V_RESERV(U_V_RES_ID, U_V_RES_DATE, U_V_APP_ID)
VALUES (SEQ_U_V_RESERV.NEXTVAL, SYSDATE, U_V_APP_ID);

COMMIT;

INSERT INTO U_V_RESERV(U_V_RES_ID, U_V_RES_DATE, U_V_APP_ID)
VALUES (SEQ_U_V_RESERV.NEXTVAL, SYSDATE, ?);

-- 긴급서비스_방문 의뢰자 노쇼 정산
-- U_V_NOS_CAL


SELECT *
FROM U_V_NOS_CAL;

DESC U_V_NOS_CAL;

DROP SEQUENCE SEQ_U_V_NOS_CAL;

CREATE SEQUENCE SEQ_U_V_NOS_CAL
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;




INSERT INTO U_V_NOS_CAL(U_V_NOS_CAL_ID, U_V_NOS_CAL_DATE, U_V_NOS_CAL_AMOUNT, U_V_NOS_CAL_ACC_DEPOSITOR, U_V_NOS_CAL_ACC_NUMBER
, BANK_ID, U_V_RES_ID)
VALUES (SEQ_U_V_NOS_CAL.NEXTVAL, SYSDATE, 72000, '김시터', '11111100111111', 1, 100);
INSERT INTO U_V_NOS_CAL(U_V_NOS_CAL_ID, U_V_NOS_CAL_DATE, U_V_NOS_CAL_AMOUNT, U_V_NOS_CAL_ACC_DEPOSITOR, U_V_NOS_CAL_ACC_NUMBER
, BANK_ID, U_V_RES_ID)
VALUES (SEQ_U_V_NOS_CAL.NEXTVAL, SYSDATE, 63000, '박시터', '33333300333333', 3, U_V_RES_ID);

COMMIT;

INSERT INTO U_V_NOS_CAL(U_V_NOS_CAL_ID, U_V_NOS_CAL_DATE, U_V_NOS_CAL_AMOUNT, U_V_NOS_CAL_ACC_DEPOSITOR, U_V_NOS_CAL_ACC_NUMBER
, BANK_ID, U_V_RES_ID)
VALUES (SEQ_U_V_NOS_CAL.NEXTVAL, SYSDATE, ?, ?, ?, ?, ?);

SELECT *
FROM BANK;



-- 긴급서비스_방문 일지
-- U_V_DIARY


SELECT *
FROM U_V_DIARY;

DESC U_V_DIARY;

DROP SEQUENCE SEQ_U_V_DIARY;

CREATE SEQUENCE SEQ_U_V_DIARY
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;



INSERT INTO U_V_DIARY(U_V_DIA_ID, U_V_DIA_CONTENT, U_V_DIA_DATE, U_V_DIA_IMG1, U_V_DIA_IMG2, U_V_DIA_IMG3, U_V_PET_CHO_ID
, U_V_RES_ID, D_MEAL_ID, D_PLAY_ID, D_POOP_ID, D_STR_ID, D_SNA_ID)
VALUES (SEQ_U_V_DIARY.NEXTVAL, '재미있는 보리의 하루~', SYSDATE, 'C://', 'C://', 'C://', 101, 100, 1, 1, 2, 3, 4);
INSERT INTO U_V_DIARY(U_V_DIA_ID, U_V_DIA_CONTENT, U_V_DIA_DATE, U_V_DIA_IMG1, U_V_DIA_IMG2, U_V_DIA_IMG3, U_V_PET_CHO_ID
, U_V_RES_ID, D_MEAL_ID, D_PLAY_ID, D_POOP_ID, D_STR_ID, D_SNA_ID)
VALUES (SEQ_U_V_DIARY.NEXTVAL, '너무귀엽고 착한 코코였습니다.~', SYSDATE, 'C://', 'C://', 'C://', U_V_PET_CHO_ID, U_V_RES_ID, 1, 2, 3, 4, 5);

COMMIT;


INSERT INTO U_V_DIARY(U_V_DIA_ID, U_V_DIA_CONTENT, U_V_DIA_DATE, U_V_DIA_IMG1, U_V_DIA_IMG2, U_V_DIA_IMG3, U_V_PET_CHO_ID
, U_V_RES_ID, D_MEAL_ID, D_PLAY_ID, D_POOP_ID, D_STR_ID, D_SNA_ID)
VALUES (SEQ_U_V_DIARY.NEXTVAL, ?, SYSDATE, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);

SELECT *
FROM DIA_SNACK;

SELECT *
FROM DIA_STROLL;

SELECT *
FROM DIA_MEAL;

SELECT *
FROM DIA_POOP;


SELECT *
FROM U_V_PET_CHO;


-- 긴급서비스 방문 펫 선택
-- U_V_PET_CHO


SELECT *
FROM U_V_PET_CHO;

DESC U_V_PET_CHO;

DROP SEQUENCE SEQ_U_V_PET_CHO;

CREATE SEQUENCE SEQ_U_V_PET_CHO
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;


SELECT *
FROM PET_SHARE;

INSERT INTO U_V_PET_CHO(U_V_PET_CHO_ID, U_V_ID, P_SHA_ID)
VALUES (SEQ_U_V_PET_CHO.NEXTVAL, 101, 103);


COMMIT;

INSERT INTO U_V_PET_CHO(U_V_PET_CHO_ID, U_V_RES_DATE, U_V_APP_ID)
VALUES (SEQ_U_V_PET_CHO.NEXTVAL, ?, ?);


-- 긴급서비스_방문 펫시터 노쇼 의뢰인 환불
-- U_V_NOS_REF


SELECT *
FROM U_V_NOS_REF;

DESC U_V_NOS_REF;

DROP SEQUENCE SEQ_U_V_NOS_REF;

CREATE SEQUENCE SEQ_U_V_NOS_REF
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;



INSERT INTO U_V_NOS_REF(U_V_NOS_REF_ID, U_V_NOS_REF_DATE, U_V_NOS_REF_AMOUNT, U_V_NOS_REF_ACC_NUM, U_V_NOS_REF_ACC_DEPOSITOR
, BANK_ID, U_V_RES_ID)
VALUES (SEQ_U_V_NOS_REF.NEXTVAL, SYSDATE, 80000, '김의뢰', '222220022222', 2, 100);
INSERT INTO U_V_NOS_REF(U_V_NOS_REF_ID, U_V_NOS_REF_DATE, U_V_NOS_REF_AMOUNT, U_V_NOS_REF_ACC_NUM, U_V_NOS_REF_ACC_DEPOSITOR
, BANK_ID, U_V_RES_ID)
VALUES (SEQ_U_V_NOS_REF.NEXTVAL, SYSDATE, 70000, '박의뢰', '4444440044444', 4, U_V_RES_ID);

COMMIT;

INSERT INTO U_V_NOS_REF(U_V_NOS_REF_ID, U_V_NOS_REF_DATE, U_V_NOS_REF_AMOUNT, U_V_NOS_REF_ACC_NUM, U_V_NOS_REF_ACC_DEPOSITOR
, BANK_ID, U_V_RES_ID)
VALUES (SEQ_U_V_NOS_REF.NEXTVAL, SYSDATE, ?, ?, ?, ?, ?);

-- 긴급서비스_방문 의뢰인 취소 환불
-- U_V_CAN_REF


SELECT *
FROM U_V_CAN_REF;

DESC U_V_CAN_REF;

DROP SEQUENCE SEQ_U_V_CAN_REF;

CREATE SEQUENCE SEQ_U_V_CAN_REF
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;



INSERT INTO U_V_CAN_REF(U_V_CAN_REF_ID, U_V_CAN_REF_DATE, U_V_CAN_REF_AMOUNT, U_V_CAN_REF_ACC_NUMBER, U_V_CAN_REF_ACC_DEPOSITOR
, BANK_ID, U_V_RES_ID)
VALUES (SEQ_U_V_CAN_REF.NEXTVAL, SYSDATE, 80000, '김의뢰', '222220022222', 2, 100);
INSERT INTO U_V_CAN_REF(U_V_CAN_REF_ID, U_V_CAN_REF_DATE, U_V_CAN_REF_AMOUNT, U_V_CAN_REF_ACC_NUMBER, U_V_CAN_REF_ACC_DEPOSITOR
, BANK_ID, U_V_RES_ID)
VALUES (SEQ_U_V_CAN_REF.NEXTVAL, SYSDATE, 63000, '박의뢰', '33333300333333', 3, U_V_RES_ID);

COMMIT;

INSERT INTO U_V_CAN_REF(U_V_CAN_REF_ID, U_V_CAN_REF_DATE, U_V_CAN_REF_AMOUNT, U_V_CAN_REF_ACC_NUMBER, U_V_CAN_REF_ACC_DEPOSITOR
, BANK_ID, U_V_RES_ID)
VALUES (SEQ_U_V_CAN_REF.NEXTVAL, SYSDATE, ?, ?, ?, ?, ?);


-- 긴급서비스_방문 펫시터정산
-- U_V_CAL


SELECT *
FROM U_V_CAL;

DESC U_V_CAL;

DROP SEQUENCE SEQ_U_V_CAL;

CREATE SEQUENCE SEQ_U_V_CAL
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;



INSERT INTO U_V_CAL(U_V_CAL_ID, U_V_CAL_DATE, U_V_CAL_AMOUNT, U_V_CAL_ACC_NUMBER, U_V_CAL_ACC_DEPOSITOR
, BANK_ID, U_V_CON_ID)
VALUES (SEQ_U_V_CAL.NEXTVAL, SYSDATE, 72000, '김시터', '11111100111111', 1, 100);
INSERT INTO U_V_CAL(U_V_CAL_ID, U_V_CAL_DATE, U_V_CAL_AMOUNT, U_V_CAL_ACC_NUMBER, U_V_CAL_ACC_DEPOSITOR
, BANK_ID, U_V_RES_ID)
VALUES (SEQ_U_V_CAL.NEXTVAL, SYSDATE, 63000, '박시터', '33333300333333', 3, U_V_RES_ID);

COMMIT;

INSERT INTO U_V_CAL(U_V_CAL_ID, U_V_CAL_DATE, U_V_CAL_AMOUNT, U_V_CAL_ACC_NUMBER, U_V_CAL_ACC_DEPOSITOR
, BANK_ID, U_V_CON_ID)
VALUES (SEQ_U_V_CAL.NEXTVAL, SYSDATE, ?, ?, ?, ?, ?);


SELECT *
FROM U_V_CONFIRM;

-- 긴급서비스_방문 기간만료 환불
-- U_V_EXPIRE


SELECT *
FROM U_V_EXPIRE;

DESC U_V_EXPIRE;

DROP SEQUENCE SEQ_U_V_EXPIRE;

CREATE SEQUENCE SEQ_U_V_EXPIRE
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;



INSERT INTO U_V_EXPIRE(U_V_EXP_ID, U_V_EXP_DATE, U_V_EXP_AMOUNT, U_V_EXP_ACC_NUMBER, U_V_EXP_ACC_DEPOSITOR
, BANK_ID, U_V_ID)
VALUES (SEQ_U_V_EXPIRE.NEXTVAL, SYSDATE, 80000, '김의뢰', '222220022222', 2, 100);
INSERT INTO U_V_EXPIRE(U_V_EXP_ID, U_V_EXP_DATE, U_V_EXP_AMOUNT, U_V_EXP_ACC_NUMBER, U_V_EXP_ACC_DEPOSITOR
, BANK_ID, U_V_ID)
VALUES (SEQ_U_V_EXPIRE.NEXTVAL, SYSDATE, 70000, '박의뢰', '4444440044444', 4, U_V_ID);

COMMIT;

INSERT INTO U_V_EXPIRE(U_V_EXP_ID, U_V_EXP_DATE, U_V_EXP_AMOUNT, U_V_EXP_ACC_NUMBER, U_V_EXP_ACC_DEPOSITOR
, BANK_ID, U_V_ID)
VALUES (SEQ_U_V_EXPIRE.NEXTVAL, SYSDATE, ?, ?, ?, ?, ?);

-- 긴급서비스_방문 요청 삭제 환불
-- U_V_DEL_REF


SELECT *
FROM U_V_DEL_REF;

DESC U_V_DEL_REF;

DROP SEQUENCE SEQ_U_V_DEL_REF;

CREATE SEQUENCE SEQ_U_V_DEL_REF
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;



INSERT INTO U_V_DEL_REF(U_V_DEL_REF_ID, U_V_DEL_REF_DATE, U_V_DEL_REF_AMOUNT, U_V_DEL_REF_NUMBER, U_V_DEL_REF_ACC_DEPOSITOR
, BANK_ID, U_V_ID)
VALUES (SEQ_U_V_DEL_REF.NEXTVAL, SYSDATE, 80000, '222220022222' ,'김의뢰', 2, 100);



COMMIT;

INSERT INTO U_V_DEL_REF(U_V_DEL_REF_ID, U_V_DEL_REF_DATE, U_V_DEL_REF_AMOUNT, U_V_DEL_REF_NUMBER, U_V_DEL_REF_ACC_DEPOSITOR
, BANK_ID, U_V_ID)
VALUES (SEQ_U_V_DEL_REF.NEXTVAL, SYSDATE, ?, ?, ?, ?, ?);


SELECT *
FROM BLOCK;


-- 긴급서비스_방문 요청 삭제 환불
-- NOTICE


SELECT *
FROM NOTICE;


DESC NOTICE;

DROP SEQUENCE SEQ_NOTICE;

CREATE SEQUENCE SEQ_NOTICE
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 99999
NOCYCLE
NOCACHE
ORDER;



INSERT INTO NOTICE(N_ID, N_TITLE, N_CONTENT, N_DATE, N_HIT, ADM_ID)
VALUES (SEQ_NOTICE.NEXTVAL, '코로나 19관련 지침', '코로나19의 확산세 증가로 인해 전국 에서 확진자가 다수 발생하는 등 대학생활이 큰 영향을 받고 있습니다. 코로나19 확산 방지에 무엇보다 중요한 것은 확진자 및 밀접접촉자와의 접촉을 빨리 확인하여 확산을 최소화하는 것입니다. '
, SYSDATE , DEFAULT, 'kiwi');

COMMIT;


INSERT INTO NOTICE(N_ID, N_TITLE, N_CONTENT, N_DATE, N_HIT, ADM_ID)
VALUES (SEQ_NOTICE.NEXTVAL, ?, ?, SYSDATE , DEFAULT, ?);





